name: gruham_yogi
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  video_player: ^2.2.10
  flutter_screenutil: ^5.0.0+2
  flutter_svg: ^1.0.0
  simple_gradient_text: ^1.2.2
  google_ml_kit:
    path: ./google_ml_kit-0.7.3
  iconsax: ^0.0.8
  camera: ^0.9.4+5
  tflite_flutter: ^0.9.0
  ffi: ^1.1.2
  flutter_image_compress: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_native_splash: ^1.3.2

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash_logo_1x.png

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/video/
    - assets/model/
    - assets/images/pose/

  fonts:
    - family: Apercu
      fonts:
        - asset: assets/fonts/apercu/Apercu-Light.otf
          weight: 300
        - asset: assets/fonts/apercu/Apercu-Regular.otf
          weight: 400
        - asset: assets/fonts/apercu/Apercu-Medium.otf
          weight: 500
        - asset: assets/fonts/apercu/Apercu-Bold.otf
          weight: 700
